os:
  - linux
  - osx
language: python
python:
  - 3.2
  - 3.3
  - 3.4
  - pypy3

# command to install dependencies
before_install:
  - pip install pytest pytest-cov
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - py.test
notifications:
  slack: talk-point:WEzco7AhrMqPwQlzhjl3aQbq
