os:
  - linux
  - osx
language: python
python:
  - 2.6
  - 2.7
  - pypy

# command to install dependencies
before_install:
  - pip install pytest pytest-cov
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - py.test
notifications:
  slack: talk-point:WEzco7AhrMqPwQlzhjl3aQbq
