#!/usr/bin/env python
import click
from pkg.cli import AppInfo
from pkg.cli import GaleraCLI


def print_version(ctx, param, value):
    if not value or ctx.resilient_parsing:
        return
    click.echo(AppInfo.version_info())
    ctx.exit()


@click.group()
@click.option('--version', is_flag=True, callback=print_version, expose_value=False, is_eager=True, help='Show Version and Licens Information.')
@click.pass_context
def main(ctx):
    pass


@main.command()
@click.option('--user', '-i' ,prompt='MySQL User:', default='debian-sys-maint', help='The MySQL User.')
@click.option('--password', '-p', prompt='MySQL password', hide_input=True, help='The Password for the MySQL User.')
@click.option('--hosts', '-h', multiple=True, help="A MySQL host, can multiple", default=('127.0.0.1',))
@click.option('--config-file', '-c', multiple=True, help="A MySQL host, can multiple", default=('127.0.0.1',))
@click.pass_obj
def check(ctx, user, password, hosts, config_file):
    try:
        GaleraCLI.check(user, password, hosts)
    except Exception as e:
        click.echo(click.style("\nException: ", fg='red')+"{0}".format(e))


if __name__ == '__main__':
    main()
