#!/usr/bin/env python
import click
from pkg import Cluster
from pkg import ClusterTable

class Parameter(object):
    def __init__(self, **kwargs):
        pass


def print_version(ctx, param, value):
    if not value or ctx.resilient_parsing:
        return
    click.echo('Version 1.2.1 Copyright TheCodeEngine\nUnder MIT License http://opensource.org/licenses/MIT')
    ctx.exit()

@click.group()
@click.option('--version', is_flag=True, callback=print_version, expose_value=False, is_eager=True, help='Show Version and Licens Information.')
@click.pass_context
def main(ctx):
    ctx.obj = Parameter()


@main.command()
@click.option('--user', '-i' ,prompt='MySQL User:', default='debian-sys-maint', help='The MySQL User.')
@click.option('--password', '-p', prompt='MySQL password', hide_input=True, help='The Password for the MySQL User.')
@click.option('--hosts', '-h', multiple=True, help="A MySQL host, can multiple", default=('127.0.0.1',))
@click.pass_obj
def galera_check(ctx, user, password, hosts):
    click.echo('\n+--- Checking Cluster Intigrity:')
    cluster = Cluster(nodes=hosts, user=user, password=password)
    with click.progressbar(length=cluster.count(), label='Fetching Data') as bar:
        cluster.fetch(bar.update)
    table = ClusterTable(cluster)
    table.render()
    

if __name__ == '__main__':
	main()
